name: Check PR

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-check-pr
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN_GH }}" > ~/.npmrc

      - uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          cache: 'yarn'


      - name: Install dependencies
        run: yarn install_packages

      - name: Check eslint
        run: yarn lint:check

      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '^(feat|fix|perf|refactor|revert|test|test|build|chore|release)([(a-z-)]*):\s[a-z0-9\s]+$' # Regex the title should match.
          prefix_case_sensitive: true
          min_length: 10
          max_length: 80
